### ISSUE TITLE
Bug: Wrong tooltip showing

### ISSUE THREAD

**Issue by nancikennedy** [Choonster-WoW-AddOns/CustomTooltips#6]
On Retail, with the latest version of CT (only) enabled, I am having a tooltip issue with some macros not showing the correct tooltip. I was able to get around this for all but one so far (by forcing them to the end of the General section by prepending a "z" in the name. But this macro:
#showtooltip
/use [@mouseover,help,nodead]@target,help,nodead][@player]Power Word: Shield

...no matter what I name it, or whether it's in the General or Player macro section persists in showing the tooltip for 17th macro in the General section. They've never been the same name and I cannot for the life of me figure out what is going on.

**Comment by Choonster** [comment]
It looks like this is related to https://github.com/Stanzilla/WoWUIBugs/issues/495 and the workaround I added for it (https://github.com/Choonster-WoW-AddOns/CustomTooltips/commit/619b13be64cf8ff7da4a12ffb469afb8195c4417). Power Word: Shield happens to have a Spell ID of 17, which is a valid macro index; so Custom Tooltips uses the tooltip from that macro. This only happens when that macro uses `#customtooltip` or `#tooltipdesc`.

Since there's no sign of the bug being fixed, I'll change Custom Tooltips to look up the macro by name instead of trying to use the index.

**Comment by Choonster** [comment]
This has been fixed in version 1.19.0, with versions 1.19.1 and 1.19.2 containing other minor changes.

I've also added this note to the AddOn description on CurseForge and WoW Interface:
> **Important:** Due to [this bug](https://github.com/Stanzilla/WoWUIBugs/issues/495) introduced by Blizzard in 10.2.0, Custom Tooltip currently requires macros to have unique names when using the default macro system with the default action bars, ElvUI or LibActionButton.
